execute if data block -396 76 -65 {Items:[{id:"minecraft:iron_ingot"}]} run function communism:bounty_1
execute if data block -396 76 -65 {Items:[{id:"minecraft:iron_block"}]} run function communism:bounty_2
execute if data block -396 76 -65 {Items:[{id:"minecraft:raw_iron"}]} run function communism:bounty_3
execute if data block -396 76 -65 {Items:[{id:"minecraft:raw_iron_block"}]} run function communism:bounty_4
execute if data block -396 76 -65 {Items:[{id:"minecraft:iron_nugget"}]} run function communism:bounty_5
execute if data block -396 76 -65 {Items:[{id:"minecraft:gold_ingot"}]} run function communism:bounty_6
execute if data block -396 76 -65 {Items:[{id:"minecraft:gold_block"}]} run function communism:bounty_7
execute if data block -396 76 -65 {Items:[{id:"minecraft:raw_gold"}]} run function communism:bounty_8
execute if data block -396 76 -65 {Items:[{id:"minecraft:raw_gold_block"}]} run function communism:bounty_9
execute if data block -396 76 -65 {Items:[{id:"minecraft:gold_nugget"}]} run function communism:bounty_10
execute if data block -396 76 -65 {Items:[{id:"minecraft:white_concrete_powder"}]} run function communism:bounty_11
execute if data block -396 76 -65 {Items:[{id:"minecraft:orange_concrete_powder"}]} run function communism:bounty_12
execute if data block -396 76 -65 {Items:[{id:"minecraft:magenta_concrete_powder"}]} run function communism:bounty_13
execute if data block -396 76 -65 {Items:[{id:"minecraft:light_blue_concrete_powder"}]} run function communism:bounty_14
execute if data block -396 76 -65 {Items:[{id:"minecraft:yellow_concrete_powder"}]} run function communism:bounty_15
execute if data block -396 76 -65 {Items:[{id:"minecraft:lime_concrete_powder"}]} run function communism:bounty_16
execute if data block -396 76 -65 {Items:[{id:"minecraft:pink_concrete_powder"}]} run function communism:bounty_17
execute if data block -396 76 -65 {Items:[{id:"minecraft:gray_concrete_powder"}]} run function communism:bounty_18
execute if data block -396 76 -65 {Items:[{id:"minecraft:light_gray_concrete_powder"}]} run function communism:bounty_19
execute if data block -396 76 -65 {Items:[{id:"minecraft:cyan_concrete_powder"}]} run function communism:bounty_20
execute if data block -396 76 -65 {Items:[{id:"minecraft:purple_concrete_powder"}]} run function communism:bounty_21
execute if data block -396 76 -65 {Items:[{id:"minecraft:blue_concrete_powder"}]} run function communism:bounty_22
execute if data block -396 76 -65 {Items:[{id:"minecraft:brown_concrete_powder"}]} run function communism:bounty_23
execute if data block -396 76 -65 {Items:[{id:"minecraft:green_concrete_powder"}]} run function communism:bounty_24
execute if data block -396 76 -65 {Items:[{id:"minecraft:red_concrete_powder"}]} run function communism:bounty_25
execute if data block -396 76 -65 {Items:[{id:"minecraft:black_concrete_powder"}]} run function communism:bounty_26
execute if data block -396 76 -65 {Items:[{id:"minecraft:white_concrete"}]} run function communism:bounty_27
execute if data block -396 76 -65 {Items:[{id:"minecraft:orange_concrete"}]} run function communism:bounty_28
execute if data block -396 76 -65 {Items:[{id:"minecraft:magenta_concrete"}]} run function communism:bounty_29
execute if data block -396 76 -65 {Items:[{id:"minecraft:light_blue_concrete"}]} run function communism:bounty_30
execute if data block -396 76 -65 {Items:[{id:"minecraft:yellow_concrete"}]} run function communism:bounty_31
execute if data block -396 76 -65 {Items:[{id:"minecraft:lime_concrete"}]} run function communism:bounty_32
execute if data block -396 76 -65 {Items:[{id:"minecraft:pink_concrete"}]} run function communism:bounty_33
execute if data block -396 76 -65 {Items:[{id:"minecraft:gray_concrete"}]} run function communism:bounty_34
execute if data block -396 76 -65 {Items:[{id:"minecraft:light_gray_concrete"}]} run function communism:bounty_35
execute if data block -396 76 -65 {Items:[{id:"minecraft:cyan_concrete"}]} run function communism:bounty_36
execute if data block -396 76 -65 {Items:[{id:"minecraft:purple_concrete"}]} run function communism:bounty_37
execute if data block -396 76 -65 {Items:[{id:"minecraft:blue_concrete"}]} run function communism:bounty_38
execute if data block -396 76 -65 {Items:[{id:"minecraft:brown_concrete"}]} run function communism:bounty_39
execute if data block -396 76 -65 {Items:[{id:"minecraft:green_concrete"}]} run function communism:bounty_40
execute if data block -396 76 -65 {Items:[{id:"minecraft:red_concrete"}]} run function communism:bounty_41
execute if data block -396 76 -65 {Items:[{id:"minecraft:black_concrete"}]} run function communism:bounty_42
execute if data block -396 76 -65 {Items:[{id:"minecraft:coal"}]} run function communism:bounty_43
execute if data block -396 76 -65 {Items:[{id:"minecraft:coal_block"}]} run function communism:bounty_44
execute if data block -396 76 -65 {Items:[{id:"minecraft:charcoal"}]} run function communism:bounty_45
execute if data block -396 76 -65 {Items:[{id:"minecraft:nether_brick"}]} run function communism:bounty_46
execute if data block -396 76 -65 {Items:[{id:"minecraft:nether_bricks"}]} run function communism:bounty_47
execute if data block -396 76 -65 {Items:[{id:"minecraft:quartz"}]} run function communism:bounty_48
execute if data block -396 76 -65 {Items:[{id:"minecraft:gilded_blackstone"}]} run function communism:bounty_49
execute if data block -396 76 -65 {Items:[{id:"minecraft:glowstone_dust"}]} run function communism:bounty_50
execute if data block -396 76 -65 {Items:[{id:"minecraft:glowstone"}]} run function communism:bounty_51
execute if data block -396 76 -65 {Items:[{id:"minecraft:magma_block"}]} run function communism:bounty_52
execute if data block -396 76 -65 {Items:[{id:"minecraft:redstone"}]} run function communism:bounty_53
execute if data block -396 76 -65 {Items:[{id:"minecraft:redstone_torch"}]} run function communism:bounty_54
execute if data block -396 76 -65 {Items:[{id:"minecraft:repeater"}]} run function communism:bounty_55
execute if data block -396 76 -65 {Items:[{id:"minecraft:comparator"}]} run function communism:bounty_56
execute if data block -396 76 -65 {Items:[{id:"minecraft:redstone_block"}]} run function communism:bounty_57
execute if data block -396 76 -65 {Items:[{id:"minecraft:redstone_lamp"}]} run function communism:bounty_58
execute if data block -396 76 -65 {Items:[{id:"minecraft:piston"}]} run function communism:bounty_59
execute if data block -396 76 -65 {Items:[{id:"minecraft:observer"}]} run function communism:bounty_60
execute if data block -396 76 -65 {Items:[{id:"minecraft:dirt"}]} run function communism:bounty_61
execute if data block -396 76 -65 {Items:[{id:"minecraft:cobblestone"}]} run function communism:bounty_62
execute if data block -396 76 -65 {Items:[{id:"minecraft:gravel"}]} run function communism:bounty_63
execute if data block -396 76 -65 {Items:[{id:"minecraft:sand"}]} run function communism:bounty_64
execute if data block -396 76 -65 {Items:[{id:"minecraft:stone"}]} run function communism:bounty_65
execute if data block -396 76 -65 {Items:[{id:"minecraft:andesite"}]} run function communism:bounty_66
execute if data block -396 76 -65 {Items:[{id:"minecraft:granite"}]} run function communism:bounty_67
execute if data block -396 76 -65 {Items:[{id:"minecraft:diorite"}]} run function communism:bounty_68
execute if data block -396 76 -65 {Items:[{id:"minecraft:grass_block"}]} run function communism:bounty_69
execute if data block -396 76 -65 {Items:[{id:"minecraft:oak_log"}]} run function communism:bounty_70
execute if data block -396 76 -65 {Items:[{id:"minecraft:birch_log"}]} run function communism:bounty_71
execute if data block -396 76 -65 {Items:[{id:"minecraft:dark_oak_log"}]} run function communism:bounty_72
execute if data block -396 76 -65 {Items:[{id:"minecraft:spruce_log"}]} run function communism:bounty_73
execute if data block -396 76 -65 {Items:[{id:"minecraft:mangrove_log"}]} run function communism:bounty_74
execute if data block -396 76 -65 {Items:[{id:"minecraft:jungle_log"}]} run function communism:bounty_75
execute if data block -396 76 -65 {Items:[{id:"minecraft:acacia_log"}]} run function communism:bounty_76
execute if data block -396 76 -65 {Items:[{id:"minecraft:cherry_log"}]} run function communism:bounty_77
execute if data block -396 76 -65 {Items:[{id:"minecraft:oak_planks"}]} run function communism:bounty_78
execute if data block -396 76 -65 {Items:[{id:"minecraft:birch_planks"}]} run function communism:bounty_79
execute if data block -396 76 -65 {Items:[{id:"minecraft:dark_oak_planks"}]} run function communism:bounty_80
execute if data block -396 76 -65 {Items:[{id:"minecraft:spruce_planks"}]} run function communism:bounty_81
execute if data block -396 76 -65 {Items:[{id:"minecraft:mangrove_planks"}]} run function communism:bounty_82
execute if data block -396 76 -65 {Items:[{id:"minecraft:jungle_planks"}]} run function communism:bounty_83
execute if data block -396 76 -65 {Items:[{id:"minecraft:acacia_planks"}]} run function communism:bounty_84
execute if data block -396 76 -65 {Items:[{id:"minecraft:cherry_planks"}]} run function communism:bounty_85
execute if data block -396 76 -65 {Items:[{id:"minecraft:lapis_lazuli"}]} run function communism:bounty_86
execute if data block -396 76 -65 {Items:[{id:"minecraft:book"}]} run function communism:bounty_87
execute if data block -396 76 -65 {Items:[{id:"minecraft:anvil"}]} run function communism:bounty_88

data remove block -396 76 -65 Items